USE [master]
GO

/****** Object:  Database [produkti]    Script Date: 10/20/2020 1:51:24 AM ******/
CREATE DATABASE [produkti]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'produkti', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\produkti.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'produkti_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\produkti_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [produkti] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [produkti].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [produkti] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [produkti] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [produkti] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [produkti] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [produkti] SET ARITHABORT OFF 
GO

ALTER DATABASE [produkti] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [produkti] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [produkti] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [produkti] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [produkti] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [produkti] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [produkti] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [produkti] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [produkti] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [produkti] SET  DISABLE_BROKER 
GO

ALTER DATABASE [produkti] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [produkti] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [produkti] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [produkti] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [produkti] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [produkti] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [produkti] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [produkti] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [produkti] SET  MULTI_USER 
GO

ALTER DATABASE [produkti] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [produkti] SET DB_CHAINING OFF 
GO

ALTER DATABASE [produkti] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [produkti] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [produkti] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [produkti] SET  READ_WRITE 
GO

