//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace produkti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_produkti
    {
        public int numri { get; set; }
        public string emri { get; set; }
        public System.DateTime dataeshtimit { get; set; }
        public decimal cmimi { get; set; }
        public string kategoria { get; set; }
        public bool pagesa { get; set; }
    }
}
